/*
ICS3U - Joshua Wang - May 17
This is the genius game, which is basically like hangman. You have to give the
program a length and it generates a random sequence of letters that you have to
guess. Once you have guessed the correct combination, you can play again and you
can always quit
 */
package my.wangjoshuageniusgamegui;

/**
 *
 * @author 340889765
 */
public class WangJoshuaGeniusGameGUI extends javax.swing.JFrame {
    //declares all the variables for the game
    int numLetters;
    int randomChar;
    int correctCounter = 0;
    int wrongCounter;
    int roundCounter = 1;
    //declares all the boolean counters
    boolean playAgainCounter = true;
    boolean gamePlaying = false;
    boolean properGuess = true;
    //declares all the arrays
    char [] secretWord = new char [10];
    char [] usersGuess = new char [10];
    //creates all the strings for printing
    String display = "*****GENIUS*****\n" +
        "How many letters in a guess? (Enter through # of char)";
    String introLetters = "";
    String userGuessString;
    /**
     * Creates new form WangJoshuaGeniusGameGUI
     */
    public WangJoshuaGeniusGameGUI() {
        initComponents();
    }
    //creates method for finding the amount of correct guesses
    public static int checkGuess(char[]secretWord, char[]usersGuess, 
            int numLetters){
        int correctCounter = 0;
        //for loop that goes through the entire array
        for(int i = 0; i<numLetters;i++){
            //compares secretWord with your guess
            if(secretWord[i]==usersGuess[i]){
                //adds one to correctCounter
                correctCounter++;
            }
        }
        //returns correctCounter
        return correctCounter;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("The Genius Game");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Number of Characters:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Guess:");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("*****GENIUS*****\nHow many letters in a guess? (Enter through # of char)");
        jScrollPane1.setViewportView(jTextArea1);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Enter");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Play Again");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(40, 40, 40))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                    .addComponent(jTextField2))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(jLabel1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButton3)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButton1)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jButton4))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Enter button for guess
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //if the game is being played
        if(gamePlaying == true){
            //resets values for a new round
            properGuess = true;
            //try statement
            try{
            //gets users guess
            userGuessString = jTextField1.getText();
                for(int i = 0; i<numLetters;i++){
                    //puts all of the chars into the array
                    usersGuess[i] = userGuessString.charAt(i);
                    //if the guess is r,g or b
                    if(usersGuess[i]=='r'||usersGuess[i]=='g'||usersGuess[i]=='b'){
                        //nothing happens
                    }else{
                        //but if guess isn't r,g or b, proper guess is false
                        properGuess = false;
                    }
                }
            //if guess is r,g or b and the length is equal to numLetters
            if(properGuess==true && userGuessString.length() == numLetters){
                //finds the amount of correct guesses
                correctCounter = checkGuess(secretWord,usersGuess,numLetters);
                //finds wrong counter with math
                wrongCounter = numLetters-correctCounter;
                //puts the guess in display
                display = display + userGuessString;
                //resets introLetters for new round
                introLetters = "";
                //for loop to numLetters
                for(int i = 0;i<numLetters;i++){
                    //inputs the array within the ||||
                    introLetters = introLetters +"| " + usersGuess[i] + " ";
                }
                //puts a space behind the |||| for the console effect
                introLetters = "                                               " 
                + "                                       " +introLetters + "|";
                //if correct counter isn't numLetters
                if(correctCounter != numLetters){
                    //increases roundCounter by 1
                    roundCounter++;
                    //put all of the new round statements into display string
                    display = display + "\n" + introLetters + "    " + correctCounter 
                    + " correct, " + wrongCounter + " incorrect" + "\nRound: " 
                    + roundCounter + "   Please guess " + numLetters 
                    + " characters rgb: ";
                    //clears the textField
                    jTextField1.setText("");
                    //prints out display
                    jTextArea1.setText(display);
                    //clears the label
                    jLabel5.setText("");
                //but if correctCounter is numLetters, which means you won
                }else if(correctCounter == numLetters){
                    //clears textField
                    jTextField1.setText("");
                    //puts all of the win statements within display
                    display = display +"\n" + introLetters + "    " + correctCounter 
                    + " correct, " + wrongCounter + " incorrect" + "\nYou won in "
                    + roundCounter + " rounds!" + "\nDo you wish to play again?";
                    //prints out display
                    jTextArea1.setText(display);
                    //you aren't playing anymore so gamePlaying is false
                    gamePlaying = false;
                    //clears the label
                    jLabel5.setText("");
                }
            //if guess isn't r,g or b and the proper length
            }else{
                //displays error message
                jLabel5.setText("Please enter a valid guess");
                //clears field
                jTextField1.setText("");
            }
            //if there is an error of index out of bounds
            }catch(IndexOutOfBoundsException e){
                //displays error message
                jLabel5.setText("Please enter a valid guess");
                //clears field
                jTextField1.setText("");
            }
    }
    }//GEN-LAST:event_jButton1ActionPerformed
//exits button
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //exits system
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
 //enter button for # of chars
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    //try statement
    try{
        //if the game isn't being played, and the playAgain button is true
        if(gamePlaying == false && playAgainCounter == true){
            //makes numLetters the text field by using parseInt
            numLetters = Integer.parseInt(jTextField2.getText());
            //if numLetters is not less than 3 or greater than 10
            if(numLetters<=10 && numLetters >= 3){
                //for loop that is based off of numLetters
                for(int i = 0; i<numLetters ; i++){
                    //creates a random number using random
                    randomChar = (int) (Math.random()*3)+1;
                    //if the random number is 1
                    if(randomChar == 1){
                        //sets secret word char as r
                        secretWord[i] = 'r';
                        //puts letter in display(for testing, shows combination)
                        display = display + "\nr";
                        jTextArea1.setText(display);
                    //if random number is 2
                    }else if(randomChar == 2){
                        //sets secret word char as g
                        secretWord[i] = 'g';
                        //puts letter in display(for testing, shows combination)
                        display = display + "\ng";
                        //prints out display
                        jTextArea1.setText(display);
                    }else if(randomChar == 3){
                        //sets secret word char as b
                        secretWord[i] = 'b';
                        //puts letter in display(for testing, shows combination)
                        display = display + "\nb";
                        //prints out displays
                        jTextArea1.setText(display);
                    }
                }
                //uses for loop based off numLetters
                for(int i = 0;i<numLetters;i++){
                    //sets introLetters up with | and userGuess array
                    introLetters = introLetters +"| " + usersGuess[i] + " ";
                }
                //puts space behind introLetters
                introLetters = "                                                   " 
                    + "                                   " +introLetters + "|";
                //sets displays with all the new round information
                display = display + "\n" + introLetters + "\nRound: " + roundCounter 
                    + "   Please guess " + numLetters + " characters rgb: ";
                //prints out display
                jTextArea1.setText(display);
                //clears the text field
                jTextField2.setText("");
                //clears the error message
                jLabel4.setText("");
                //sets gamePlaying as true because you are now playing
                gamePlaying = true;
                //you can't playAgain
                playAgainCounter = false;
            //if the number isn't between 3-10
            }else{
                //displays error message
                jLabel4.setText("Please enter a number between 3-10 inclusive");
                //clears field
                jTextField2.setText("");
            }
        }
    //catch statement
    }catch(NumberFormatException e){
        //displays error message
        jLabel4.setText("Please enter a number between 3-10 inclusive");
        //clears field
        jTextField2.setText("");
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //if the game isn't being played
        if(gamePlaying == false){
            //resets the game by resetting all values
            correctCounter = 0;
            roundCounter = 1;
            secretWord = new char [10];
            usersGuess = new char [10];
            introLetters = "";
            //sets display to a new round
            display = "*****GENIUS*****\n" +
                    "How many letters in a guess? (Enter through # of char)";
            //you can now play again
            playAgainCounter = true;
            //prints out display
            jTextArea1.setText(display);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WangJoshuaGeniusGameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WangJoshuaGeniusGameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WangJoshuaGeniusGameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WangJoshuaGeniusGameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WangJoshuaGeniusGameGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
